//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float4x4 gFixedView;               // Offset:  384 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  448 Size:    12
//   float cbPerObjectPad1;             // Offset:  460 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  464 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  472 Size:     8 [unused]
//   float gNearZ;                      // Offset:  480 Size:     4 [unused]
//   float gFarZ;                       // Offset:  484 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  488 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  492 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  496 Size:    16
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  512
//       float FalloffStart;            // Offset:  524
//       float3 Direction;              // Offset:  528
//       float FalloffEnd;              // Offset:  540
//       float3 Position;               // Offset:  544
//       float SpotPower;               // Offset:  556
//
//   } gLights[16];                     // Offset:  512 Size:   768
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gsamAnisotropicWrap               sampler      NA          NA      S0             s4      1 
// gDiffuseMap                       texture  float4          2d      T0             t0      1 
// cbPass                            cbuffer      NA          NA     CB0            cb1      1 
// cbMaterial                        cbuffer      NA          NA     CB1            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1:1][43], dynamicIndexed, space=0
dcl_constantbuffer CB1[2:2][2], immediateIndexed, space=0
dcl_sampler S0[4:4], mode_default, space=0
dcl_resource_texture2d (float,float,float,float) T0[0:0], space=0
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_output o0.xyzw
dcl_temps 8
sample r0.xyzw, v3.xyxx, T0[0].xyzw, S0[4]
mul r1.xyzw, r0.xyzw, CB1[2][0].xyzw
dp3 r0.w, v2.xyzx, v2.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v2.xyzx
add r3.xyz, -v1.xyzx, CB0[1][28].xyzx
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
add r2.w, -CB1[2][1].w, l(1.000000)
mul r3.w, r2.w, l(256.000000)
mad r2.w, r2.w, l(256.000000), l(8.000000)
mov r4.xyzw, l(0,0,0,0)
loop 
  ige r5.x, r4.w, l(3)
  breakc_nz r5.x
  imul null, r5.x, r4.w, l(3)
  dp3 r5.y, -CB0[1][r5.x + 33].xyzx, r2.xyzx
  max r5.y, r5.y, l(0.000000)
  mul r5.yzw, r5.yyyy, CB0[1][r5.x + 32].xxyz
  mad r6.xyz, r3.xyzx, r0.wwww, -CB0[1][r5.x + 33].xyzx
  dp3 r6.w, r6.xyzx, r6.xyzx
  rsq r6.w, r6.w
  mul r6.xyz, r6.wwww, r6.xyzx
  dp3 r6.w, r6.xyzx, r2.xyzx
  max r6.w, r6.w, l(0.000000)
  log r6.w, r6.w
  mul r6.w, r3.w, r6.w
  exp r6.w, r6.w
  mul r6.w, r2.w, r6.w
  mul r6.w, r6.w, l(0.125000)
  dp3_sat r5.x, r6.xyzx, -CB0[1][r5.x + 33].xyzx
  add r5.x, -r5.x, l(1.000000)
  add r6.xyz, -CB1[2][1].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r7.x, r5.x, r5.x
  mul r7.x, r7.x, r7.x
  mul r5.x, r5.x, r7.x
  mad r6.xyz, r6.xyzx, r5.xxxx, CB1[2][1].xyzx
  mul r7.xyz, r6.wwww, r6.xyzx
  mad r6.xyz, r6.xyzx, r6.wwww, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r6.xyz, r7.xyzx, r6.xyzx
  mad r6.xyz, r0.xyzx, CB1[2][0].xyzx, r6.xyzx
  mad r4.xyz, r6.xyzx, r5.yzwy, r4.xyzx
  iadd r4.w, r4.w, l(1)
endloop 
mad o0.xyz, CB0[1][31].xyzx, r1.xyzx, r4.xyzx
mov o0.w, r1.w
ret 
// Approximately 47 instruction slots used
