//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float4x4 gFixedView;               // Offset:  384 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  448 Size:    12
//   float cbPerObjectPad1;             // Offset:  460 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  464 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  472 Size:     8 [unused]
//   float gNearZ;                      // Offset:  480 Size:     4 [unused]
//   float gFarZ;                       // Offset:  484 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  488 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  492 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  496 Size:    16 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  512
//       float FalloffStart;            // Offset:  524
//       float3 Direction;              // Offset:  528
//       float FalloffEnd;              // Offset:  540
//       float3 Position;               // Offset:  544
//       float SpotPower;               // Offset:  556
//
//   } gLights[16];                     // Offset:  512 Size:   768 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// cbPerObject                       cbuffer      NA          NA     CB0            cb0      1 
// cbPass                            cbuffer      NA          NA     CB1            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xy          2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
vs_5_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[0:0][4], immediateIndexed, space=0
dcl_constantbuffer CB1[1:1][29], immediateIndexed, space=0
dcl_input v0.xyz
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xy
dcl_temps 2
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, CB0[0][0].xyzw
dp4 r1.y, r0.xyzw, CB0[0][1].xyzw
dp4 r1.z, r0.xyzw, CB0[0][2].xyzw
dp4 r0.w, r0.xyzw, CB0[0][3].xyzw
add r0.xyz, r1.xyzx, CB1[1][28].xyzx
dp4 r1.x, r0.xyzw, CB1[1][16].xyzw
dp4 r1.y, r0.xyzw, CB1[1][17].xyzw
dp4 r1.z, r0.xyzw, CB1[1][19].xyzw
mov o0.xyzw, r1.xyzz
mov o1.xyz, v0.xyzx
mov o2.xyz, l(0,0,0,0)
mov o3.xy, l(0,0,0,0)
ret 
// Approximately 15 instruction slots used
